CREATE TABLE song (
  ID       MEDIUMINT    NOT NULL AUTO_INCREMENT,
  TITLE    VARCHAR(100) NOT NULL,
  DURATION MEDIUMINT    NOT NULL,
  RECORD_ID MEDIUMINT    NOT NULL DEFAULT 0,
  PRIMARY KEY (ID),
  FOREIGN KEY (RECORD_ID) REFERENCES record(ID)
);
